version: '3.1'

services:

   mysql:
      image: mysql
      restart: always
      environment:
         MYSQL_DATABASE: somedb
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: user1
         MYSQL_PASSWORD: pass
         TZ: Europe/Samara
      volumes:
         - ./dbinit.sql:/data/application/init.sql
      ports:
      - 3306:3306

   phpmyadmin:
      image: phpmyadmin:latest
      restart: always
      ports:
      - 8080:80
      environment:
         PMA_HOST: mysql
         PMA_USER: user1
         PMA_PASSWORD: pass
      links:
      - mysql