version: '3.1'

services:
   
#   rest:
#      image: restspring
#      restart: always
#      depends_on:
#         mysql:
#            condition: service_healthy
#      ports:
#         - 8081:8081

   mysql:
      image: mysql:latest
      restart: always
      environment:
         MYSQL_DATABASE: somedb
         MYSQL_ROOT_PASSWORD: root
         MYSQL_USER: user1
         MYSQL_PASSWORD: pass
         TZ: Europe/Samara
      #volumes:
         #- ./dbinit.sql:/docker-entrypoint-initdb.d/init.sql
      healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 10s
            retries: 20
      ports:
      - 3306:3306

   phpmyadmin:
      image: phpmyadmin:latest
      restart: always
      ports:
      - 8080:80
      environment:
         PMA_HOST: mysql
         PMA_USER: user1
         PMA_PASSWORD: pass
      links:
      - mysql